// pixl-engine export-phaser - emits a standalone web bundle that runs a
// PixlProjectDocument via @pixlland/phaser-runtime + Phaser 4.

import { copyFile, cp, mkdir, mkdtemp, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PixlProjectShape, PixlSceneObjectShape } from '../schema.js';

export const EXPORT_PHASER_FORMAT = 'pixlplayground-export-phaser' as const;
export const EXPORT_PHASER_FORMAT_VERSION = 1 as const;

export interface ExportPhaserOptions {
  assetBaseUrl?: string;
  title?: string;
  pageBackground?: string;
  exportedAt?: number;
}

export interface ExportPhaserManifest {
  format: typeof EXPORT_PHASER_FORMAT;
  formatVersion: typeof EXPORT_PHASER_FORMAT_VERSION;
  exportedAt: number;
  projectId: string;
  projectName: string;
  activeSceneId: string;
  sceneCount: number;
  assetCount: number;
  engine: { name?: string; version?: string } | undefined;
  runtime: 'phaser-2d';
}

export interface ExportPhaserResult {
  indexHtml: string;
  mainJsSource: string;
  manifest: ExportPhaserManifest;
  assetPaths: string[];
  rewrittenProject: PixlProjectShape;
  rewriteCount: number;
}

type PixlObjectWithChildren = PixlSceneObjectShape & { children?: PixlObjectWithChildren[] };

const normalizeAssetPath = (value: string): string => value.replace(/^public\//, '');

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const buildIndexHtml = (title: string, pageBackground: string): string => {
  const safeTitle = escapeHtml(title);
  const safeBg = escapeHtml(pageBackground);
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    `<title>${safeTitle}</title>`,
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
    '<style>',
    `html,body,#game{margin:0;padding:0;width:100%;height:100%;background:${safeBg};overflow:hidden;font-family:system-ui,sans-serif;color:#eee}`,
    'canvas{display:block;width:100vw!important;height:100vh!important}',
    '#error{position:fixed;top:0;left:0;right:0;padding:12px 16px;background:#3a0a0a;color:#fca5a5;font:13px/1.4 ui-monospace,monospace;white-space:pre-wrap;display:none;z-index:9999}',
    '#error.show{display:block}',
    '</style>',
    '</head>',
    '<body>',
    '<div id="game"></div>',
    '<div id="error"></div>',
    '<script type="module" src="./main.js"></script>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
};

const buildMainJsSource = (assetBaseUrl: string): string => {
  const safeBase = JSON.stringify(assetBaseUrl);
  return [
    '// Generated by pixl-engine export-phaser. Do not edit by hand.',
    "import { Game } from '@pixlland/phaser-runtime';",
    '',
    'const showError = (message) => {',
    "  const el = document.getElementById('error');",
    "  if (el) { el.textContent = message; el.classList.add('show'); }",
    "  console.error('[pixl-export-phaser]', message);",
    '};',
    '',
    'const resize = (runtime) => {',
    '  const game = runtime.phaserGame;',
    '  if (!game?.scale?.resize) return;',
    '  game.scale.resize(window.innerWidth, window.innerHeight);',
    '};',
    '',
    '(async () => {',
    '  try {',
    "    const resp = await fetch('./project.pixlproject.json');",
    "    if (!resp.ok) throw new Error('Failed to fetch project.pixlproject.json: ' + resp.status);",
    '    const project = await resp.json();',
    '    const runtime = Game.fromPixlProject(project, {',
    "      parent: 'game',",
    '      width: window.innerWidth,',
    '      height: window.innerHeight,',
    `      assetBaseUrl: ${safeBase},`,
    '    });',
    '    await runtime.play();',
    '    resize(runtime);',
    "    window.addEventListener('resize', () => resize(runtime));",
    "    window.__pixlPhaserRuntime = runtime;",
    '  } catch (err) {',
    '    showError(err && err.stack ? err.stack : String(err));',
    '  }',
    '})();',
    '',
  ].join('\n');
};

interface AssetLookup {
  byUrl: Map<string, string>;
}

const buildAssetLookup = (project: PixlProjectShape): AssetLookup => {
  const byUrl = new Map<string, string>();
  for (const entry of project.assets?.entries ?? []) {
    if (!entry.path) continue;
    byUrl.set(entry.path, entry.path);
    byUrl.set(normalizeAssetPath(entry.path), entry.path);
    if (entry.url) {
      byUrl.set(entry.url, entry.path);
      byUrl.set(normalizeAssetPath(entry.url), entry.path);
    }
  }
  return { byUrl };
};

const rewriteValue = (value: unknown, lookup: AssetLookup): { value: unknown; rewritten: boolean } => {
  if (typeof value !== 'string') return { value, rewritten: false };
  const dest = lookup.byUrl.get(value) ?? lookup.byUrl.get(normalizeAssetPath(value));
  if (!dest || dest === value) return { value, rewritten: false };
  return { value: dest, rewritten: true };
};

const URL_FIELDS = ['imageUrl', 'texturePath', 'url', 'tilemapPath'] as const;

const rewriteData = (
  data: Record<string, unknown>,
  lookup: AssetLookup,
  counter: { count: number },
): Record<string, unknown> => {
  let changed = false;
  const out: Record<string, unknown> = { ...data };
  for (const field of URL_FIELDS) {
    const result = rewriteValue(out[field], lookup);
    if (result.rewritten) {
      out[field] = result.value;
      counter.count += 1;
      changed = true;
    }
  }
  if (Array.isArray(out.tilesets)) {
    const nextTilesets = out.tilesets.map((tileset) => {
      if (!tileset || typeof tileset !== 'object' || Array.isArray(tileset)) return tileset;
      const record = tileset as Record<string, unknown>;
      const result = rewriteValue(record.path, lookup);
      if (!result.rewritten) return tileset;
      counter.count += 1;
      changed = true;
      return { ...record, path: result.value };
    });
    out.tilesets = nextTilesets;
  }
  return changed ? out : data;
};

const rewriteObject = (
  object: PixlObjectWithChildren,
  lookup: AssetLookup,
  counter: { count: number },
): PixlObjectWithChildren => {
  let changed = false;
  const data = object.data ? rewriteData(object.data, lookup, counter) : object.data;
  if (data !== object.data) changed = true;

  let components = object.components;
  if (components) {
    const next = components.map((component) => {
      const newData = rewriteData(component.data, lookup, counter);
      return newData === component.data ? component : { ...component, data: newData };
    });
    if (next.some((component, index) => component !== components![index])) {
      components = next;
      changed = true;
    }
  }

  let children = object.children;
  if (children) {
    const nextChildren = children.map((child) => rewriteObject(child, lookup, counter));
    if (nextChildren.some((child, index) => child !== children![index])) {
      children = nextChildren;
      changed = true;
    }
  }

  return changed ? { ...object, data, components, children } : object;
};

export const rewritePhaserAssetUrlsInProject = (
  project: PixlProjectShape,
): { project: PixlProjectShape; rewriteCount: number } => {
  const lookup = buildAssetLookup(project);
  if (lookup.byUrl.size === 0) return { project, rewriteCount: 0 };
  const counter = { count: 0 };
  const scenes = project.scenes.map((scene) => {
    const rootObjects = scene.rootObjects.map((object) =>
      rewriteObject(object as PixlObjectWithChildren, lookup, counter),
    );
    if (rootObjects.some((object, index) => object !== scene.rootObjects[index])) {
      return { ...scene, rootObjects };
    }
    return scene;
  });
  if (scenes.some((scene, index) => scene !== project.scenes[index])) {
    return { project: { ...project, scenes }, rewriteCount: counter.count };
  }
  return { project, rewriteCount: counter.count };
};

export const exportProjectToPhaser = (
  project: PixlProjectShape,
  options: ExportPhaserOptions = {},
): ExportPhaserResult => {
  if (project.format !== 'pixlplayground-project') {
    throw new Error(
      `exportProjectToPhaser: unexpected project format "${project.format}". Expected "pixlplayground-project".`,
    );
  }
  const activeScene = project.scenes.find((scene) => scene.id === project.activeSceneId);
  if (!activeScene) {
    throw new Error(
      `exportProjectToPhaser: activeSceneId "${project.activeSceneId}" not found in project.scenes.`,
    );
  }
  if (activeScene.kind !== '2d' && activeScene.kind !== 'hybrid') {
    throw new Error(
      `exportProjectToPhaser: active scene "${activeScene.id}" is kind="${activeScene.kind}", expected "2d" or "hybrid". Use export-three for 3D projects.`,
    );
  }

  const assetSourceBase = options.assetBaseUrl ?? '.';
  const title = options.title ?? project.name;
  const pageBackground = options.pageBackground ?? '#000';
  const assetEntries = project.assets?.entries ?? [];
  const assetPaths = Array.from(
    new Set(assetEntries.map((entry) => entry.path).filter((path): path is string => Boolean(path))),
  );
  const { project: rewrittenProject, rewriteCount } = rewritePhaserAssetUrlsInProject(project);

  return {
    indexHtml: buildIndexHtml(title, pageBackground),
    mainJsSource: buildMainJsSource(assetSourceBase),
    rewrittenProject,
    rewriteCount,
    assetPaths,
    manifest: {
      format: EXPORT_PHASER_FORMAT,
      formatVersion: EXPORT_PHASER_FORMAT_VERSION,
      exportedAt: options.exportedAt ?? 0,
      projectId: project.id,
      projectName: project.name,
      activeSceneId: project.activeSceneId,
      sceneCount: project.scenes.length,
      assetCount: assetPaths.length,
      engine: project.engine
        ? { name: project.engine.name, version: project.engine.version }
        : undefined,
      runtime: 'phaser-2d',
    },
  };
};

export interface RunExportPhaserOptions extends ExportPhaserOptions {
  assetSearchPaths?: string[];
  skipBundle?: boolean;
  sourcemap?: boolean;
  minify?: boolean;
  cliPackageDir?: string;
}

export interface RunExportPhaserResult {
  outDir: string;
  fileCount: number;
  assetCount: number;
  missingAssets: Array<{ id: string; path: string; url?: string }>;
  copiedDirs: string[];
  bundleSizeBytes: number;
  rewriteCount: number;
}

const fileExists = async (path: string): Promise<boolean> => {
  try {
    return (await stat(path)).isFile();
  } catch {
    return false;
  }
};

const dirExists = async (path: string): Promise<boolean> => {
  try {
    return (await stat(path)).isDirectory();
  } catch {
    return false;
  }
};

const defaultCliPackageDir = (): string => {
  const here = fileURLToPath(import.meta.url);
  return resolve(dirname(here), '..', '..');
};

const copyAssetEntry = async (
  entry: { id: string; path: string; url?: string },
  projectDir: string,
  outDir: string,
  searchPaths: string[],
): Promise<boolean> => {
  const candidates: string[] = [];
  const pushVariants = (base: string, ref: string): void => {
    candidates.push(resolve(base, ref));
    const normalized = normalizeAssetPath(ref);
    if (normalized !== ref) candidates.push(resolve(base, normalized));
  };
  for (const base of [projectDir, ...searchPaths]) {
    if (entry.url) pushVariants(base, entry.url);
    if (entry.path) pushVariants(base, entry.path);
  }
  for (const candidate of candidates) {
    if (await fileExists(candidate)) {
      const dest = resolve(outDir, entry.path);
      await mkdir(dirname(dest), { recursive: true });
      await copyFile(candidate, dest);
      return true;
    }
  }
  return false;
};

const sumJsBytesRecursive = async (dir: string): Promise<number> => {
  let total = 0;
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) total += await sumJsBytesRecursive(full);
    else if (entry.isFile() && entry.name.endsWith('.js')) total += (await stat(full)).size;
  }
  return total;
};

const copyRuntimeDir = async (projectDir: string, outDir: string): Promise<boolean> => {
  const runtimeDir = resolve(projectDir, 'runtime');
  if (!(await dirExists(runtimeDir))) return false;
  await cp(runtimeDir, resolve(outDir, 'runtime'), { recursive: true });
  return true;
};

export const runExportPhaser = async (
  projectPath: string,
  outDir: string,
  options: RunExportPhaserOptions = {},
): Promise<RunExportPhaserResult> => {
  const absProject = resolve(process.cwd(), projectPath);
  const absOut = resolve(process.cwd(), outDir);
  const projectDir = dirname(absProject);
  const project = JSON.parse(await readFile(absProject, 'utf8')) as PixlProjectShape;

  const exportedAt = options.exportedAt ?? Date.now();
  const result = exportProjectToPhaser(project, { ...options, exportedAt });

  await mkdir(absOut, { recursive: true });
  await writeFile(
    resolve(absOut, 'project.pixlproject.json'),
    `${JSON.stringify(result.rewrittenProject, null, 2)}\n`,
    'utf8',
  );
  await writeFile(
    resolve(absOut, 'manifest.json'),
    `${JSON.stringify(result.manifest, null, 2)}\n`,
    'utf8',
  );

  const assetEntries = project.assets?.entries ?? [];
  const missingAssets: RunExportPhaserResult['missingAssets'] = [];
  const searchPaths = options.assetSearchPaths ?? [];
  let copiedCount = 0;
  const copiedDirs: string[] = [];

  if (options.skipBundle) {
    for (const entry of assetEntries) {
      if (!entry.path) continue;
      const ok = await copyAssetEntry(entry, projectDir, absOut, searchPaths);
      if (ok) copiedCount += 1;
      else missingAssets.push({ id: entry.id, path: entry.path, url: entry.url });
    }
    if (await copyRuntimeDir(projectDir, absOut)) copiedDirs.push('runtime');
    await writeFile(resolve(absOut, 'index.html'), result.indexHtml, 'utf8');
    await writeFile(resolve(absOut, 'main.js'), result.mainJsSource, 'utf8');
    return {
      outDir: absOut,
      fileCount: 4 + copiedCount + copiedDirs.length,
      assetCount: copiedCount,
      missingAssets,
      copiedDirs,
      bundleSizeBytes: Buffer.byteLength(result.mainJsSource, 'utf8'),
      rewriteCount: result.rewriteCount,
    };
  }

  const cliPackageDir = options.cliPackageDir ?? defaultCliPackageDir();
  const tmpBase = join(cliPackageDir, '.tmp');
  await mkdir(tmpBase, { recursive: true });
  const tmpRoot = await mkdtemp(join(tmpBase, 'export-phaser-root-'));
  const tmpPublic = await mkdtemp(join(tmpBase, 'export-phaser-public-'));
  let bundleSizeBytes = 0;

  try {
    await writeFile(resolve(tmpRoot, 'index.html'), result.indexHtml, 'utf8');
    await writeFile(resolve(tmpRoot, 'main.js'), result.mainJsSource, 'utf8');

    for (const entry of assetEntries) {
      if (!entry.path) continue;
      const ok = await copyAssetEntry(entry, projectDir, tmpPublic, searchPaths);
      if (ok) copiedCount += 1;
      else missingAssets.push({ id: entry.id, path: entry.path, url: entry.url });
    }
    if (await copyRuntimeDir(projectDir, tmpPublic)) copiedDirs.push('runtime');

    const phaserRuntimeEntry = resolve(
      cliPackageDir,
      'node_modules',
      '@pixlland',
      'phaser-runtime',
      'dist',
      'index.js',
    );

    const vite = await import('vite');
    await vite.build({
      configFile: false,
      root: tmpRoot,
      publicDir: tmpPublic,
      logLevel: 'error',
      base: './',
      resolve: {
        alias: {
          '@pixlland/phaser-runtime': phaserRuntimeEntry,
        },
      },
      build: {
        outDir: absOut,
        emptyOutDir: false,
        target: 'es2022',
        sourcemap: options.sourcemap === true,
        ...(options.minify === false ? { minify: false as const } : {}),
      },
    });
    bundleSizeBytes = await sumJsBytesRecursive(resolve(absOut, 'assets'));
  } finally {
    await rm(tmpRoot, { recursive: true, force: true });
    await rm(tmpPublic, { recursive: true, force: true });
  }

  return {
    outDir: absOut,
    fileCount: 3 + copiedCount + copiedDirs.length,
    assetCount: copiedCount,
    missingAssets,
    copiedDirs,
    bundleSizeBytes,
    rewriteCount: result.rewriteCount,
  };
};

export const printExportPhaserResult = (result: RunExportPhaserResult): void => {
  console.log('pixl-engine export-phaser');
  console.log(`  out:           ${result.outDir}`);
  console.log(`  files:         ${result.fileCount}`);
  console.log(`  assets copied: ${result.assetCount}`);
  console.log(`  bundle bytes:  ${result.bundleSizeBytes.toLocaleString()}`);
  console.log(`  url rewrites:  ${result.rewriteCount}`);
  if (result.copiedDirs.length > 0) {
    console.log(`  copied dirs:   ${result.copiedDirs.join(', ')}`);
  }
  if (result.missingAssets.length > 0) {
    console.log(`  missing:       ${result.missingAssets.length}`);
    for (const missing of result.missingAssets.slice(0, 5)) {
      console.log(`    - ${missing.path}${missing.url ? ` (url: ${missing.url})` : ''}`);
    }
    if (result.missingAssets.length > 5) {
      console.log(`    ... +${result.missingAssets.length - 5} more`);
    }
  }
};
