// pixl-engine export-runtime — emits a standalone web bundle for the
// project's GAME runtime (the JS file referenced by p.game.source.runtimeFile),
// not the engine's editorial snapshot.
//
// Distinct from export-three:
//   - export-three   bundles @pixlland/three-runtime + the project doc; the
//                    result is a viewer of the editor's view of the scene.
//   - export-runtime bundles the game's own main.js (which has its own
//                    Three.js setup, input loop, physics, HUD). The result
//                    is the game, playable.
//
// Typical project shape (Harvest Rush 3D):
//   <projectDir>/
//     project.pixlproject.json       (engine snapshot — not used here)
//     runtime/src/main.js            (the game)
//     runtime/src/styles.css         (game UI)
//     assets/vendor/...              (binaries the game fetches)
//     levels/...                     (level/save data, optional)
//
// p.game.source.runtimeFile points at the entry relative to either projectDir
// or projectDir/runtime/. The command resolves whichever exists. The Vite
// build then bundles that file + transitive imports + CSS, and the runner
// copies sibling asset dirs (assets/, levels/) verbatim into the output.

import { mkdir, writeFile, readFile, copyFile, stat, rm, mkdtemp, readdir, cp } from 'node:fs/promises';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import type { PixlProjectShape } from '../schema.js';

// ---------------------------------------------------------------------------
// Public API (pure)
// ---------------------------------------------------------------------------

export const EXPORT_RUNTIME_FORMAT = 'pixlplayground-export-runtime' as const;
export const EXPORT_RUNTIME_FORMAT_VERSION = 1 as const;

export interface ExportRuntimeOptions {
  /** `<title>` text. Defaults to `project.name`. */
  title?: string;
  /** CSS background of the host page. Defaults to `#000`. */
  pageBackground?: string;
  /**
   * Deterministic timestamp for the manifest. Tests pin this; production
   * leaves it undefined and the runner stamps Date.now().
   */
  exportedAt?: number;
}

export interface ExportRuntimeManifest {
  format: typeof EXPORT_RUNTIME_FORMAT;
  formatVersion: typeof EXPORT_RUNTIME_FORMAT_VERSION;
  exportedAt: number;
  projectId: string;
  projectName: string;
  runtimeEntry: string;
  runtime: 'standalone-game';
}

export interface ExportRuntimeResult {
  indexHtml: string;
  /** Tiny bridge module: `import '<absolute-path-to-game-main.js>'`. Vite chases the import. */
  entryJsSource: string;
  manifest: ExportRuntimeManifest;
}

// ---------------------------------------------------------------------------
// Templates
// ---------------------------------------------------------------------------

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');

const buildIndexHtml = (title: string, pageBackground: string): string => {
  const safeTitle = escapeHtml(title);
  const safeBg = escapeHtml(pageBackground);
  return [
    '<!doctype html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="utf-8">',
    `<title>${safeTitle}</title>`,
    '<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">',
    '<style>',
    `html,body{margin:0;padding:0;height:100%;background:${safeBg};overflow:hidden;font-family:system-ui,sans-serif;color:#eee}`,
    'canvas{display:block}',
    '#error{position:fixed;top:0;left:0;right:0;padding:12px 16px;background:#3a0a0a;color:#fca5a5;font:13px/1.4 ui-monospace,monospace;white-space:pre-wrap;display:none;z-index:9999}',
    '#error.show{display:block}',
    '</style>',
    '</head>',
    '<body>',
    '<div id="error"></div>',
    '<script type="module" src="./entry.js"></script>',
    '</body>',
    '</html>',
    '',
  ].join('\n');
};

const buildEntryJsSource = (absoluteRuntimePath: string): string => {
  // JSON.stringify gives us a quoted path with escapes; Vite resolves it via
  // its own absolute-path import handling (works on macOS, Linux, Windows).
  const ref = JSON.stringify(absoluteRuntimePath);
  return [
    '// Generated by pixl-engine export-runtime. Do not edit by hand.',
    '// This is a 3-line shim — the real game lives at the imported path.',
    'window.addEventListener(\'error\', (e) => {',
    '  const el = document.getElementById(\'error\');',
    '  if (el) { el.textContent = String(e.error?.stack ?? e.message ?? e); el.classList.add(\'show\'); }',
    '});',
    'window.addEventListener(\'unhandledrejection\', (e) => {',
    '  const el = document.getElementById(\'error\');',
    '  if (el) { el.textContent = String(e.reason?.stack ?? e.reason ?? e); el.classList.add(\'show\'); }',
    '});',
    `import ${ref};`,
    '',
  ].join('\n');
};

// ---------------------------------------------------------------------------
// Pure exporter
// ---------------------------------------------------------------------------

/**
 * Returns the runtime entry path relative to a project doc, OR null if the
 * project doesn't declare one. Doesn't touch the filesystem — the I/O wrapper
 * checks existence and tries the `runtime/` fallback.
 */
export const extractRuntimeEntry = (project: PixlProjectShape): string | null => {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const game = project.game as any;
  const fromSource = game?.source?.runtimeFile;
  if (typeof fromSource === 'string' && fromSource.length > 0) return fromSource;
  return null;
};

export const exportProjectToRuntime = (
  project: PixlProjectShape,
  absoluteRuntimePath: string,
  options: ExportRuntimeOptions = {},
): ExportRuntimeResult => {
  if (project.format !== 'pixlplayground-project') {
    throw new Error(
      `exportProjectToRuntime: unexpected project format "${project.format}". Expected "pixlplayground-project".`,
    );
  }

  const title = options.title ?? project.name;
  const pageBackground = options.pageBackground ?? '#000';

  const indexHtml = buildIndexHtml(title, pageBackground);
  const entryJsSource = buildEntryJsSource(absoluteRuntimePath);

  const manifest: ExportRuntimeManifest = {
    format: EXPORT_RUNTIME_FORMAT,
    formatVersion: EXPORT_RUNTIME_FORMAT_VERSION,
    exportedAt: options.exportedAt ?? 0,
    projectId: project.id,
    projectName: project.name,
    runtimeEntry: absoluteRuntimePath,
    runtime: 'standalone-game',
  };

  return { indexHtml, entryJsSource, manifest };
};

// ---------------------------------------------------------------------------
// I/O wrapper
// ---------------------------------------------------------------------------

export interface RunExportRuntimeOptions extends ExportRuntimeOptions {
  /**
   * Override runtimeFile lookup. Defaults to project.game.source.runtimeFile.
   * Useful when the project doc doesn't declare a runtime entry but you want
   * to bundle one anyway.
   */
  runtimeFile?: string;
  /**
   * Directories (relative to projectDir) to copy verbatim into the bundle.
   * Defaults to ['assets', 'levels']. Missing dirs are silently skipped.
   * The game's main.js fetches binaries from these subpaths.
   */
  assetDirs?: string[];
  /** Skip Vite bundling and emit raw entry files. Tests use this. */
  skipBundle?: boolean;
  /** Pass-through to vite.build({ build: { sourcemap } }). */
  sourcemap?: boolean;
  /** Pass-through to vite.build({ build: { minify: false } }) when set to false. */
  minify?: boolean;
  /** Override CLI package dir for module resolution. Tests use this. */
  cliPackageDir?: string;
}

export interface RunExportRuntimeResult {
  outDir: string;
  fileCount: number;
  /** Absolute path of the resolved runtime entry (`runtime/src/main.js`). */
  runtimeEntry: string;
  /** Total bytes of bundle JS chunks under `<outDir>/assets/`. */
  bundleSizeBytes: number;
  /** Subdir copies that succeeded (`assets/`, `levels/`, etc.). */
  copiedDirs: string[];
  /** Subdirs that were requested but not found on disk. */
  missingDirs: string[];
}

const fileExists = async (path: string): Promise<boolean> => {
  try {
    const s = await stat(path);
    return s.isFile();
  } catch {
    return false;
  }
};

const dirExists = async (path: string): Promise<boolean> => {
  try {
    const s = await stat(path);
    return s.isDirectory();
  } catch {
    return false;
  }
};

const defaultCliPackageDir = (): string => {
  const here = fileURLToPath(import.meta.url);
  return resolve(dirname(here), '..', '..');
};

// Recursively sum bytes of every .js file under `dir`.
const sumJsBytesRecursive = async (dir: string): Promise<number> => {
  let total = 0;
  let entries;
  try {
    entries = await readdir(dir, { withFileTypes: true });
  } catch {
    return 0;
  }
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      total += await sumJsBytesRecursive(full);
    } else if (entry.isFile() && entry.name.endsWith('.js')) {
      total += (await stat(full)).size;
    }
  }
  return total;
};

/**
 * Locate the runtime entry on disk. Tries `<projectDir>/<runtimeFile>` first;
 * falls back to `<projectDir>/runtime/<runtimeFile>` (the Pixlland convention
 * where game code lives under a `runtime/` subdir alongside the project doc).
 */
const resolveRuntimeFile = async (
  projectDir: string,
  runtimeFile: string,
): Promise<string> => {
  const direct = resolve(projectDir, runtimeFile);
  if (await fileExists(direct)) return direct;
  const underRuntimeDir = resolve(projectDir, 'runtime', runtimeFile);
  if (await fileExists(underRuntimeDir)) return underRuntimeDir;
  throw new Error(
    `export-runtime: could not locate runtime entry "${runtimeFile}". ` +
      `Tried "${direct}" and "${underRuntimeDir}".`,
  );
};

export const runExportRuntime = async (
  projectPath: string,
  outDir: string,
  options: RunExportRuntimeOptions = {},
): Promise<RunExportRuntimeResult> => {
  const absProject = resolve(process.cwd(), projectPath);
  const absOut = resolve(process.cwd(), outDir);
  const projectDir = dirname(absProject);

  const raw = await readFile(absProject, 'utf8');
  const project = JSON.parse(raw) as PixlProjectShape;

  const runtimeFile = options.runtimeFile ?? extractRuntimeEntry(project);
  if (!runtimeFile) {
    throw new Error(
      'export-runtime: project does not declare game.source.runtimeFile and no --runtime-file was passed.',
    );
  }
  const resolvedRuntime = await resolveRuntimeFile(projectDir, runtimeFile);

  const exportedAt = options.exportedAt ?? Date.now();
  const result = exportProjectToRuntime(project, resolvedRuntime, {
    ...options,
    exportedAt,
  });

  await mkdir(absOut, { recursive: true });
  await writeFile(
    resolve(absOut, 'manifest.json'),
    `${JSON.stringify(result.manifest, null, 2)}\n`,
    'utf8',
  );

  // Copy asset sibling dirs (assets/, levels/, ...) into the bundle. The
  // game's main.js fetches binaries via relative paths like `./assets/...`.
  const requestedDirs = options.assetDirs ?? ['assets', 'levels'];
  const copiedDirs: string[] = [];
  const missingDirs: string[] = [];
  for (const sub of requestedDirs) {
    const src = resolve(projectDir, sub);
    if (await dirExists(src)) {
      await cp(src, resolve(absOut, sub), { recursive: true });
      copiedDirs.push(sub);
    } else {
      missingDirs.push(sub);
    }
  }

  if (options.skipBundle) {
    await writeFile(resolve(absOut, 'index.html'), result.indexHtml, 'utf8');
    await writeFile(resolve(absOut, 'entry.js'), result.entryJsSource, 'utf8');
    const bundleSizeBytes = Buffer.byteLength(result.entryJsSource, 'utf8');
    const fileCount = 3 + copiedDirs.length; // index.html + entry.js + manifest.json + copied dirs (counted as 1 each)
    return {
      outDir: absOut,
      fileCount,
      runtimeEntry: resolvedRuntime,
      bundleSizeBytes,
      copiedDirs,
      missingDirs,
    };
  }

  const cliPackageDir = options.cliPackageDir ?? defaultCliPackageDir();
  const tmpBase = join(cliPackageDir, '.tmp');
  await mkdir(tmpBase, { recursive: true });
  const tmpRoot = await mkdtemp(join(tmpBase, 'export-runtime-root-'));

  let bundleSizeBytes = 0;
  try {
    await writeFile(resolve(tmpRoot, 'index.html'), result.indexHtml, 'utf8');
    await writeFile(resolve(tmpRoot, 'entry.js'), result.entryJsSource, 'utf8');

    const vite = await import('vite');
    await vite.build({
      configFile: false,
      root: tmpRoot,
      logLevel: 'error',
      base: './',
      // resolvedRuntime sits OUTSIDE tmpRoot — explicitly let Vite read its
      // directory and the project's runtime tree.
      server: { fs: { allow: [tmpRoot, dirname(resolvedRuntime), projectDir] } },
      build: {
        outDir: absOut,
        emptyOutDir: false,
        target: 'es2022',
        sourcemap: options.sourcemap === true,
        ...(options.minify === false ? { minify: false as const } : {}),
      },
    });
    bundleSizeBytes = await sumJsBytesRecursive(resolve(absOut, 'assets'));
  } finally {
    await rm(tmpRoot, { recursive: true, force: true });
  }

  // fileCount: 2 hand-written (manifest.json + index.html-from-Vite) +
  // Vite chunks + copied dirs.
  const fileCount = 2 + copiedDirs.length;

  return {
    outDir: absOut,
    fileCount,
    runtimeEntry: resolvedRuntime,
    bundleSizeBytes,
    copiedDirs,
    missingDirs,
  };
};

export const printExportRuntimeResult = (result: RunExportRuntimeResult): void => {
  // eslint-disable-next-line no-console
  console.log('pixl-engine export-runtime');
  console.log(`  out:          ${result.outDir}`);
  console.log(`  runtime:      ${result.runtimeEntry}`);
  console.log(`  files:        ${result.fileCount}`);
  console.log(`  bundle bytes: ${result.bundleSizeBytes.toLocaleString()}`);
  if (result.copiedDirs.length > 0) {
    console.log(`  copied dirs:  ${result.copiedDirs.join(', ')}`);
  }
  if (result.missingDirs.length > 0) {
    console.log(`  missing dirs: ${result.missingDirs.join(', ')}`);
  }
};
