import { mkdir, writeFile, access } from 'node:fs/promises';
import { join, resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import type {
  EngineVersionsManifest,
  PixlProjectShape,
  PixlRuntimeKind,
  PixlSceneKind,
  PixlSceneObjectShape,
  PixlSceneShape,
} from '../schema.js';
import { PIXL_PROJECT_FORMAT, PIXL_PROJECT_VERSION } from '../schema.js';
import { findEngineManifest } from './manifest-loader.js';

export type ProjectKind = '2d' | '3d';

export interface NewProjectOptions {
  name: string;
  targetDir: string;
  kind: ProjectKind;
  force?: boolean;
}

export interface NewProjectResult {
  projectDir: string;
  projectFile: string;
  kind: ProjectKind;
  runtime: PixlRuntimeKind;
}

const DEFAULT_FOLDERS = [
  'Assets/3D_Models',
  'Assets/Sprites',
  'Assets/Tilemaps',
  'Assets/Textures',
  'Assets/Audio',
  'Assets/VFX',
  'Assets/Materials',
  'Assets/Prefabs',
  'Scenes',
  'Scripts',
  'ProjectSettings',
  'Builds',
];

const PROJECT_GITIGNORE = `# PixlPlayground project — generated by pixl-engine new
Builds/
node_modules/
.DS_Store
*.log
*.pre-migrate.*.json
`;

const slugify = (value: string): string =>
  value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 60) || 'untitled';

const exists = async (path: string): Promise<boolean> => {
  try {
    await access(path);
    return true;
  } catch {
    return false;
  }
};

const buildSceneFor = (kind: ProjectKind, sceneId: string): PixlSceneShape => {
  if (kind === '3d') {
    return {
      id: sceneId,
      name: 'Main',
      kind: '3d' as PixlSceneKind,
      rootObjects: buildBlank3DObjects(),
      camera: {
        id: 'main-camera',
        name: 'Main Camera',
        position: [10, 8, 10],
        target: [0, 0, 0],
        fov: 50,
        near: 0.1,
        far: 1000,
      },
      environment: {
        background: '#87ceeb',
        ambientLight: '#ffffff',
        ambientIntensity: 0.7,
        sunColor: '#fffaf0',
        sunIntensity: 0.85,
      },
      physics: { engine: 'rapier', gravity: [0, -9.81, 0] },
    };
  }

  // 2D scene: camera defined with only the fields that apply to ortho/Phaser cameras.
  // 3D-only fields (fov, near, far) are omitted; the editor renders this kind through
  // the Phaser viewport which has its own camera model.
  return {
    id: sceneId,
    name: 'Main',
    kind: '2d' as PixlSceneKind,
    rootObjects: [],
    camera: {
      id: 'main-camera-2d',
      name: 'Main Camera 2D',
      position: [0, 0, 0],
      target: [0, 0, 0],
    },
    environment: {
      background: '#101822',
      ambientLight: '#ffffff',
      ambientIntensity: 1,
    },
    physics: { engine: 'arcade', gravity: [0, 980] },
  };
};

const buildRuntime = (kind: ProjectKind): { primary: PixlRuntimeKind; renderers: string[]; physics: string[] } => {
  if (kind === '3d') {
    return { primary: 'three-3d', renderers: ['three'], physics: ['rapier'] };
  }
  return { primary: 'phaser-2d', renderers: ['phaser'], physics: ['arcade'] };
};

const component = (id: string, type: string, data: Record<string, unknown>) => ({
  id,
  type,
  enabled: true,
  data,
});

const buildBlank3DObjects = (): PixlSceneObjectShape[] => [
  {
    id: 'sunlight-main',
    name: 'Sun Light',
    type: 'sunlight',
    transform: {
      position: [50, 100, 50],
      rotation: [-Math.PI / 3, Math.PI / 4, 0],
      scale: [1, 1, 1],
    },
    visible: true,
    locked: false,
    components: [
      component('sunlight-main-light', 'pixl.light3d', {
        intensity: 1.5,
        castShadow: true,
        sunElevation: 45,
        sunAzimuth: 180,
      }),
    ],
    data: { editor: { color: '#ffffff', isStatic: true } },
  },
  {
    id: 'main-camera',
    name: 'Main Camera',
    type: 'camera',
    transform: {
      position: [0, 10, 15],
      rotation: [0, 0, 0],
      scale: [1, 1, 1],
    },
    visible: true,
    locked: false,
    components: [
      component('main-camera-camera', 'pixl.camera3d', {
        mode: 'third-person',
        distance: 15,
        height: 10,
        fov: 60,
        followPlayer: true,
        targetId: 'main-player',
        smoothing: 0.1,
      }),
    ],
    data: { editor: { color: '#ffffff' } },
  },
  {
    id: 'main-player',
    name: 'Player',
    type: 'player',
    tags: ['player'],
    transform: {
      position: [0, 1, 0],
      rotation: [0, 0, 0],
      scale: [1, 2, 1],
    },
    visible: true,
    locked: false,
    components: [
      component('main-player-player', 'pixl.player', {
        movementMode: 'free',
        speed: 10,
        jumpForce: 12,
        gravity: 30,
        maxHealth: 100,
      }),
      component('main-player-primitive', 'pixl.primitive', {
        shape: 'box',
        size: { x: 1, y: 2, z: 1 },
        color: '#4a90e2',
      }),
    ],
    data: { editor: { color: '#4a90e2', isStatic: false } },
  },
  {
    id: 'ground-1',
    name: 'Ground',
    type: 'box',
    transform: {
      position: [0, -0.1, 0],
      rotation: [0, 0, 0],
      scale: [100, 0.2, 100],
    },
    visible: true,
    locked: false,
    components: [
      component('ground-1-primitive', 'pixl.primitive', {
        shape: 'box',
        size: { x: 100, y: 0.2, z: 100 },
        color: '#3d3d3d',
        receiveShadow: true,
      }),
      component('ground-1-physics', 'pixl.physics', {
        bodyType: 'fixed',
        colliderShape: 'cuboid',
        mass: 0,
        friction: 0.85,
        restitution: 0.05,
        colliders: [{ type: 'cuboid', hx: 50, hy: 0.1, hz: 50 }],
      }),
    ],
    data: { editor: { color: '#3d3d3d', isStatic: true } },
  },
];

export const buildProjectDocument = (
  options: NewProjectOptions,
  manifest: EngineVersionsManifest,
  now: number = Date.now(),
  id: string = `project_${randomUUID()}`,
): PixlProjectShape => {
  const sceneId = 'main';
  const slug = slugify(options.name);
  const runtime = buildRuntime(options.kind);
  const runtimeDeps = manifest.runtimes[runtime.primary]?.dependencies ?? {};

  return {
    format: PIXL_PROJECT_FORMAT,
    version: PIXL_PROJECT_VERSION,
    id,
    slug,
    name: options.name,
    createdAt: now,
    savedAt: now,
    activeSceneId: sceneId,
    scenes: [buildSceneFor(options.kind, sceneId)],
    assets: { root: 'Assets', folders: [...DEFAULT_FOLDERS], entries: [] },
    engine: {
      name: 'PixlPlayground',
      version: manifest.engine.version,
      schemaVersion: manifest.schemaVersion,
      runtimeManifest: {
        runtime: runtime.primary,
        dependencies: { ...runtimeDeps },
      },
    },
    runtime,
    editor: {
      mode: options.kind,
      transformSpace: 'world',
      snapEnabled: false,
      snapTranslate: 1,
      snapRotate: 15,
      snapScale: 0.25,
      selectedSceneId: sceneId,
      layoutPreset: 'default',
    },
    game: {
      templateId: null,
      script: '// Pixlland game script\n// Escreva sua logica aqui.\n',
    },
  };
};

const scaffoldFolder = async (root: string, folder: string): Promise<void> => {
  const folderPath = join(root, folder);
  await mkdir(folderPath, { recursive: true });
  await writeFile(join(folderPath, '.gitkeep'), '', 'utf8');
};

export const runNew = async (options: NewProjectOptions): Promise<NewProjectResult> => {
  const absoluteDir = resolve(process.cwd(), options.targetDir);
  if ((await exists(absoluteDir)) && !options.force) {
    throw new Error(`Diretorio "${absoluteDir}" ja existe. Use --force pra sobrescrever.`);
  }

  const { manifest } = await findEngineManifest(process.cwd(), { startKind: 'directory' });

  await mkdir(absoluteDir, { recursive: true });
  await Promise.all(DEFAULT_FOLDERS.map((folder) => scaffoldFolder(absoluteDir, folder)));

  const projectDoc = buildProjectDocument(options, manifest);
  const projectFile = join(absoluteDir, 'project.pixlproject.json');
  await Promise.all([
    writeFile(projectFile, `${JSON.stringify(projectDoc, null, 2)}\n`, 'utf8'),
    writeFile(join(absoluteDir, '.gitignore'), PROJECT_GITIGNORE, 'utf8'),
  ]);

  return {
    projectDir: absoluteDir,
    projectFile,
    kind: options.kind,
    runtime: projectDoc.runtime!.primary as PixlRuntimeKind,
  };
};

export const printNewResult = (result: NewProjectResult): void => {
  console.log(`pixl-engine new — projeto criado`);
  console.log(`  dir:      ${result.projectDir}`);
  console.log(`  arquivo:  ${result.projectFile}`);
  console.log(`  kind:     ${result.kind}`);
  console.log(`  runtime:  ${result.runtime}`);
  console.log('');
  console.log('Proximos passos:');
  console.log(`  - cd ${result.projectDir}`);
  console.log(`  - pixl-engine validate ${result.projectFile}`);
  console.log(`  - abrir o projeto no editor PixlPlayground`);
};
